### ISSUE TITLE
Discuss a conference to submit the paper, to have a "deadline"

### ISSUE THREAD

**Issue by eduardoafontana** [SwarmDebugging/SwarmDbgPharo#7]
This task needs to be prepared.

**Comment by StevenCostiou** [comment]
Si je comprends bien on bouge cette discussion vers gitlab ?
Donc il faudrait close cette issue ?

**Comment by eduardoafontana** [comment]
Exactly. This issue was opened before the decision of use Gitlab for paper tasks.
There is already one equivalent there.
Thus, I am closing this here.
